# New file: generate_medllama.py (GGUF + llama-cpp-python)

from llama_cpp import Llama
from query import search_chunks

# Path to your GGUF model
MODEL_PATH = "models/medllama-3-8B.Q4_K_M.gguf"

print("🔄 Loading GGUF quantized MedLLaMA model using llama-cpp-python...")

# Load model
llm = Llama(
    model_path=MODEL_PATH,
    n_ctx=2048,
    n_threads=8,         # adjust based on your CPU
    n_gpu_layers=20,     # use GPU for top layers if available, or set to 0 for CPU only
    verbose=False
)

print("✅ GGUF model loaded!")

def build_prompt(query, chunks):
    context = "\n\n".join(
        f"File: {chunk['file']} | Chunk ID: {chunk['chunk_id']}\n{chunk['preview']}"
        for chunk in chunks
    )

    system_prompt = (
        "You are a helpful clinical assistant specialized in CVICU nursing policies. "
        "Use the provided policy excerpts to answer the user's question as accurately and completely as possible. "
        "Only use relevant clinical information such as administration, dosage, monitoring, adverse effects, precautions, and indications. "
        "Include exact dosages, infusion details, and monitoring instructions when provided. "
        "Ignore any content related to legal disclaimers, institutional boilerplate, headers, page numbers, or footnotes. "
        "If the answer is not directly stated, use your best clinical judgment based on the context."
    )

    prompt = f"<s>[INST] {system_prompt}\n\nContext:\n{context}\n\nQuestion: {query}\n\nAnswer: [/INST]"
    return prompt

def generate_answer(query):
    top_chunks = search_chunks(query)
    prompt = build_prompt(query, top_chunks)

    print("\n🧠 Prompt Sent to LLM:\n")
    print(prompt)

    output = llm(prompt, max_tokens=350, temperature=0.7)
    answer = (
        output.get("choices", [{}])[0]
        .get("text", "[No response generated by model]")
        .strip()
    )

    if not answer:
        answer = "[⚠️ Model returned no answer. You may need to increase context or review prompt quality.]"

    print("\n📚 Sources:")
    for chunk in top_chunks:
        print(f"- {chunk['file']} (Chunk ID: {chunk['chunk_id']})")

    print("\n🩺 Generated Answer:\n")
    print(answer)

if __name__ == "__main__":
    while True:
        query = input("\nAsk a clinical question (or type 'exit'): ")
        if query.lower() == "exit":
            break
        generate_answer(query)
